name: Deploy to GitHub Pages

on:
    schedule:
        - cron: "0 0,12 * * *"
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: yarn

            - name: Generate data
              run: yarn generate
              env:
                  API_KEY: ${{ secrets.API_KEY }}

            - name: Build
              run: yarn build
              env:
                  PUBLIC_PATH: /videogames/

            - name: Prepare for deployment
              run: touch dist/.nojekyll

            - name: Deploy to Github Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v2.0.0
              with:
                  target_branch: gh-pages
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
